#!/bin/bash
set -euo pipefail

if [[ $# -ne 1 || ! "$1" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
    echo 'Usage: bash scripts/build-release.sh vMAJOR.MINOR.PATCH' >&2
    exit 64
fi

release_tag=$1
repo_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"
generated_source="$repo_root/Sources/TeamsCLI/BuildVersion.generated.swift"

# Refuse to overwrite another build's input or a file left by an interrupted build.
if ! (set -o noclobber; : > "$generated_source") 2>/dev/null; then
    echo "Generated version source already exists: $generated_source" >&2
    echo 'Wait for any release build to finish, or remove the stale file before retrying.' >&2
    exit 1
fi
trap 'rm -f "$generated_source"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

cat > "$generated_source" <<EOF
// Generated by scripts/build-release.sh; do not edit.
#if TEAMS_RELEASE_BUILD
enum BuildVersion {
    static let value = "${release_tag#v}"
}
#endif
EOF

swift build -c release -Xswiftc -DTEAMS_RELEASE_BUILD
reported_version=$(.build/release/teams-cli --version)
if [[ "$reported_version" != "teams-cli ${release_tag#v}" ]]; then
    echo 'The release executable does not report the requested version.' >&2
    exit 1
fi
